# kittymux-keys.conf — GENERATED by install.sh. Edit kittymux-keys.conf.tpl
# in the kittymux repo instead; rerun install.sh to regenerate.
# @KITTYMUX_HOME@ expands to the repo's absolute path.

# ============================================
# TMUX PASSTHROUGH — tmux owns ONLY keys it binds with `bind -n`.
# Anything else passed through becomes a dead key inside tmux.
# The defaults cover common binds: S-arrows = tmux windows,
# C-M-arrows = tmux session cycle, C-M-z = kill-window.
# Adjust to match your ~/.tmux.conf.
# ============================================
map --when-focus-on cmdline:tmux shift+left
map --when-focus-on cmdline:tmux shift+right
map --when-focus-on cmdline:tmux ctrl+alt+left
map --when-focus-on cmdline:tmux ctrl+alt+right
map --when-focus-on cmdline:tmux ctrl+alt+z

# ============================================
# TABS — contextual placement, session-scoped nav
# ============================================
map ctrl+alt+enter       launch --location=hsplit --cwd=current
map ctrl+shift+enter     launch --location=vsplit --cwd=current
map ctrl+alt+t           launch --type=background @KITTYMUX_HOME@/bin/mux-newtab.sh --next
map ctrl+alt+shift+t     launch --type=background @KITTYMUX_HOME@/bin/mux-newtab.sh
map ctrl+shift+t         launch --type=background @KITTYMUX_HOME@/bin/mux-newtab.sh --home
map ctrl+alt+r           set_tab_title
map ctrl+alt+n           new_os_window_with_cwd

map shift+left           launch --type=background @KITTYMUX_HOME@/bin/mux-nav.sh prev
map shift+right          launch --type=background @KITTYMUX_HOME@/bin/mux-nav.sh next
map ctrl+alt+1           launch --type=background @KITTYMUX_HOME@/bin/mux-nav.sh 1
map ctrl+alt+2           launch --type=background @KITTYMUX_HOME@/bin/mux-nav.sh 2
map ctrl+alt+3           launch --type=background @KITTYMUX_HOME@/bin/mux-nav.sh 3
map ctrl+alt+4           launch --type=background @KITTYMUX_HOME@/bin/mux-nav.sh 4
map ctrl+alt+5           launch --type=background @KITTYMUX_HOME@/bin/mux-nav.sh 5
map ctrl+alt+6           launch --type=background @KITTYMUX_HOME@/bin/mux-nav.sh 6
map ctrl+alt+7           launch --type=background @KITTYMUX_HOME@/bin/mux-nav.sh 7
map ctrl+alt+8           launch --type=background @KITTYMUX_HOME@/bin/mux-nav.sh 8
map ctrl+alt+9           launch --type=background @KITTYMUX_HOME@/bin/mux-nav.sh 9

map ctrl+shift+comma     move_tab_backward
map ctrl+shift+period    move_tab_forward
map ctrl+alt+shift+left  move_tab_backward
map ctrl+alt+shift+right move_tab_forward

# ============================================
# PANES — vim-style nav, detach, zoom
# ============================================
map ctrl+alt+h           neighboring_window left
map ctrl+alt+j           neighboring_window down
map ctrl+alt+k           neighboring_window up
map ctrl+alt+l           neighboring_window right
# NOTE: ctrl+alt+arrows is claimed by some WMs (e.g. Hyprland's scrolling
# layout uses it for layoutmsg focus). Pane arrows live on shift+alt.
map shift+alt+left       neighboring_window left
map shift+alt+down       neighboring_window down
map shift+alt+up         neighboring_window up
map shift+alt+right      neighboring_window right
map ctrl+alt+o           nth_window -1
map ctrl+alt+d           detach_window new-tab-right
map ctrl+alt+shift+d     detach_window ask

# ============================================
# HUDS — location, agent usage, agent jump
# ============================================
map ctrl+alt+i           launch --type=overlay --cwd=current @KITTYMUX_HOME@/bin/mux-cwd.sh
map ctrl+alt+shift+i     launch --type=overlay --cwd=current @KITTYMUX_HOME@/bin/mux-cwd.sh --detail
map ctrl+alt+u           launch --type=overlay /usr/bin/python3 @KITTYMUX_HOME@/bin/mux-usage.py
# agent picker: every agent pane across windows/sessions + live preview
# (ctrl+alt+g, not +a — ctrl+alt+a is Hyprland's swapcol on this setup)
map ctrl+alt+g           launch --type=overlay @KITTYMUX_HOME@/bin/mux-agents.sh
# ctrl+alt+b — sidebar command deck (hover/click, live preview, jump to tab)
map ctrl+alt+b           kitten @KITTYMUX_HOME@/python/sidebar-kit.py
# ctrl+alt+shift+b — toggle the sidebar deck as a persistent docked panel (Wayland)
map ctrl+alt+shift+b     launch --type=background @KITTYMUX_HOME@/bin/mux-panel toggle
# ctrl+alt+y — jump to the next agent waiting on you (round-robin, longest-waiting first)
map ctrl+alt+y           launch --type=background @KITTYMUX_HOME@/bin/mux-agents.sh --next-waiting
# ctrl+alt+shift+g — new agent in its own git worktree + tab
map ctrl+alt+shift+g     launch --type=overlay --cwd=current @KITTYMUX_HOME@/bin/mux-agent-new
# send a prompt to a background agent pane without switching focus
map ctrl+alt+semicolon   launch --type=overlay @KITTYMUX_HOME@/bin/mux-send.sh
# per-window activity state feeding the picker's busy/waiting markers
watcher @KITTYMUX_HOME@/python/pane-state.py
map ctrl+alt+shift+e     launch --type=background @KITTYMUX_HOME@/bin/mux-edge.sh
# ctrl+alt+backslash — this window's bar: sidebar → slim rail → hidden (zen), like a browser sidebar
map ctrl+alt+backslash   launch --type=background @KITTYMUX_HOME@/bin/kittymux layout mode cycle
# ctrl+alt+shift+[ — narrower sidebar
map ctrl+alt+shift+bracketleft  launch --type=background @KITTYMUX_HOME@/bin/kittymux layout width -2
# ctrl+alt+shift+] — wider sidebar
map ctrl+alt+shift+bracketright launch --type=background @KITTYMUX_HOME@/bin/kittymux layout width +2
# ctrl+alt+shift+l — pick a bar layout preset (sidebar, rail, right, bottom, top, zen)
map ctrl+alt+shift+l     launch --type=overlay @KITTYMUX_HOME@/bin/kittymux layout pick

# ============================================
# RESIZE, SCROLLBACK & HELP
# ctrl+alt+/         — keymap overlay (this list, parsed live)
# ctrl+alt+shift+/   — last command's output in pager
# ctrl+alt+q         — close current pane (confirms if a process runs)
# ctrl+alt+[ / ]     — jump between shell prompts in scrollback
# alt+shift+h/l/j/k  — resize pane narrower/wider/taller/shorter
# ============================================
map ctrl+alt+slash        launch --type=overlay /usr/bin/python3 @KITTYMUX_HOME@/bin/mux-keys.py
map ctrl+alt+shift+slash  show_last_command_output
map ctrl+alt+q            close_window_with_confirmation
map ctrl+alt+bracketleft  scroll_to_prompt -1
map ctrl+alt+bracketright scroll_to_prompt 1
map alt+shift+h           resize_window narrower 1
map alt+shift+l           resize_window wider 1
map alt+shift+j           resize_window taller 1
map alt+shift+k           resize_window shorter 1

# ============================================
# LAYOUTS
# ============================================
map ctrl+alt+space       next_layout
map ctrl+alt+z           layout_action maximize
# ctrl+alt+0: rebalance (ctrl+alt+equal collides with Hyprland colresize)
map ctrl+alt+0           layout_action equalize

# ============================================
# SESSIONS — Kitty Home is the one shortcut to remember
# ============================================
map ctrl+shift+space     launch --type=overlay @KITTYMUX_HOME@/bin/mux-sessionizer
map ctrl+alt+shift+n     launch --type=overlay @KITTYMUX_HOME@/bin/mux-sessionizer
map ctrl+alt+shift+m     launch --type=overlay @KITTYMUX_HOME@/bin/mux-movetab.sh
map ctrl+alt+shift+s     launch --type=overlay @KITTYMUX_HOME@/bin/mux-save.sh
map ctrl+alt+shift+a     launch --type=background @KITTYMUX_HOME@/bin/mux-cycle.sh last
map ctrl+alt+comma       launch --type=background @KITTYMUX_HOME@/bin/mux-cycle.sh prev
map ctrl+alt+period      launch --type=background @KITTYMUX_HOME@/bin/mux-cycle.sh next

# ============================================
# PROJECT PICKER + SCRATCH CONFIG TAB
# ============================================
map ctrl+alt+shift+p     launch --type=overlay @KITTYMUX_HOME@/bin/mux-projects.sh
map ctrl+alt+shift+k     launch --type=background @KITTYMUX_HOME@/bin/mux-scratch.sh --cwd @KITTYMUX_HOME@ -- nvim

# ============================================
# OTHER
# ============================================
map ctrl+shift+alt+r     combine : load_config_file : launch --type=background notify-send -i kitty -t 2000 "Kitty" "Config reloaded"
map ctrl+alt+shift+w     close_tab
map shift+enter          send_text normal,application \x1b[13;2u
