# kittymux-leader.conf — GENERATED by `install.sh --leader`. Edit
# kittymux-leader.conf.tpl in the kittymux repo instead; rerun install.sh to regenerate.
#
# Leader mode: tap @KITTYMUX_LEADER@, then ONE key. No modifier chords to fight your WM,
# and it reads like tmux's prefix — but it is kitty-native (modal mappings).
# The tab bar shows a LEADER badge while the mode is armed; press ? for the full card.
# Anything unmapped (or 2s of silence) cancels the mode.
#
# Each `map --mode leader KEY …` line is preceded by a `# description` line; the
# which-key card (leader ?) is generated from exactly those pairs.

map --new-mode leader --on-action end --on-unknown end --timeout 2.0 @KITTYMUX_LEADER@

# focus pane ←
map --mode leader h neighboring_window left
# focus pane ↓
map --mode leader j neighboring_window down
# focus pane ↑
map --mode leader k neighboring_window up
# focus pane →
map --mode leader l neighboring_window right
# last pane
map --mode leader o nth_window -1
# split right (cwd)
map --mode leader backslash launch --location=vsplit --cwd=current
# split down (cwd)
map --mode leader minus launch --location=hsplit --cwd=current
# zoom / unzoom pane
map --mode leader z layout_action maximize
# equalize panes
map --mode leader equal layout_action equalize
# next layout
map --mode leader space next_layout
# close pane (confirms if busy)
map --mode leader x close_window_with_confirmation
# pane → its own tab
map --mode leader d detach_window new-tab-right

# new tab beside this one
map --mode leader c launch --type=background @KITTYMUX_HOME@/bin/mux-newtab.sh --next
# next tab
map --mode leader n launch --type=background @KITTYMUX_HOME@/bin/mux-nav.sh next
# previous tab
map --mode leader p launch --type=background @KITTYMUX_HOME@/bin/mux-nav.sh prev
# jump to tab 1
map --mode leader 1 launch --type=background @KITTYMUX_HOME@/bin/mux-nav.sh 1
# jump to tab 2
map --mode leader 2 launch --type=background @KITTYMUX_HOME@/bin/mux-nav.sh 2
# jump to tab 3
map --mode leader 3 launch --type=background @KITTYMUX_HOME@/bin/mux-nav.sh 3
# jump to tab 4
map --mode leader 4 launch --type=background @KITTYMUX_HOME@/bin/mux-nav.sh 4
# jump to tab 5
map --mode leader 5 launch --type=background @KITTYMUX_HOME@/bin/mux-nav.sh 5
# jump to tab 6
map --mode leader 6 launch --type=background @KITTYMUX_HOME@/bin/mux-nav.sh 6
# jump to tab 7
map --mode leader 7 launch --type=background @KITTYMUX_HOME@/bin/mux-nav.sh 7
# jump to tab 8
map --mode leader 8 launch --type=background @KITTYMUX_HOME@/bin/mux-nav.sh 8
# jump to tab 9
map --mode leader 9 launch --type=background @KITTYMUX_HOME@/bin/mux-nav.sh 9
# rename tab
map --mode leader r set_tab_title
# close tab
map --mode leader shift+x close_tab

# Kitty Home — sessions
map --mode leader s launch --type=overlay @KITTYMUX_HOME@/bin/mux-sessionizer
# project picker
map --mode leader shift+p launch --type=overlay @KITTYMUX_HOME@/bin/mux-projects.sh

# agent picker
map --mode leader a launch --type=overlay @KITTYMUX_HOME@/bin/mux-agents.sh
# next agent waiting on you
map --mode leader w launch --type=background @KITTYMUX_HOME@/bin/mux-agents.sh --next-waiting
# new agent in its own worktree
map --mode leader g launch --type=overlay --cwd=current @KITTYMUX_HOME@/bin/mux-agent-new
# send a prompt to an agent
map --mode leader semicolon launch --type=overlay @KITTYMUX_HOME@/bin/mux-send.sh
# sidebar deck
map --mode leader b kitten @KITTYMUX_HOME@/python/sidebar-kit.py
# docked sidebar panel (toggle)
map --mode leader shift+b launch --type=background @KITTYMUX_HOME@/bin/mux-panel toggle
# agent usage HUD
map --mode leader u launch --type=overlay /usr/bin/python3 @KITTYMUX_HOME@/bin/mux-usage.py
# location pill
map --mode leader i launch --type=overlay --cwd=current @KITTYMUX_HOME@/bin/mux-cwd.sh
# cycle tab bar edge (this window)
map --mode leader e launch --type=background @KITTYMUX_HOME@/bin/kittymux layout edge cycle
# bar: sidebar → rail → hidden
map --mode leader t launch --type=background @KITTYMUX_HOME@/bin/kittymux layout mode cycle
# narrower sidebar
map --mode leader bracketleft launch --type=background @KITTYMUX_HOME@/bin/kittymux layout width -2
# wider sidebar
map --mode leader bracketright launch --type=background @KITTYMUX_HOME@/bin/kittymux layout width +2
# bar layout presets
map --mode leader shift+l launch --type=overlay @KITTYMUX_HOME@/bin/kittymux layout pick
# this card
map --mode leader shift+slash launch --type=overlay /usr/bin/python3 @KITTYMUX_HOME@/bin/mux-keys.py --leader
