# kittymux-keys.conf — GENERATED by install.sh. Edit kittymux-keys.conf.tpl
# in the kittymux repo instead; rerun install.sh to regenerate.
# @KITTYMUX_HOME@ expands to the repo's absolute path.

# ============================================
# TMUX PASSTHROUGH — tmux owns ONLY keys it binds with `bind -n`.
# Anything else passed through becomes a dead key inside tmux.
# The defaults cover common binds: S-arrows = tmux windows,
# C-M-arrows = tmux session cycle, C-M-z = kill-window.
# Adjust to match your ~/.tmux.conf.
# ============================================
map --when-focus-on cmdline:tmux shift+left
map --when-focus-on cmdline:tmux shift+right
map --when-focus-on cmdline:tmux ctrl+alt+left
map --when-focus-on cmdline:tmux ctrl+alt+right
map --when-focus-on cmdline:tmux ctrl+alt+z

# ============================================
# TABS — contextual placement, session-scoped nav
# ============================================
map ctrl+alt+enter       launch --location=hsplit --cwd=current
map ctrl+shift+enter     launch --location=vsplit --cwd=current
map ctrl+alt+t           launch --type=background @KITTYMUX_HOME@/bin/mux-newtab.sh --next
map ctrl+alt+shift+t     launch --type=background @KITTYMUX_HOME@/bin/mux-newtab.sh
map ctrl+shift+t         launch --type=background @KITTYMUX_HOME@/bin/mux-newtab.sh --home
map ctrl+alt+r           set_tab_title
map ctrl+alt+n           new_os_window_with_cwd

map shift+left           launch --type=background @KITTYMUX_HOME@/bin/mux-nav.sh prev
map shift+right          launch --type=background @KITTYMUX_HOME@/bin/mux-nav.sh next
map ctrl+alt+1           launch --type=background @KITTYMUX_HOME@/bin/mux-nav.sh 1
map ctrl+alt+2           launch --type=background @KITTYMUX_HOME@/bin/mux-nav.sh 2
map ctrl+alt+3           launch --type=background @KITTYMUX_HOME@/bin/mux-nav.sh 3
map ctrl+alt+4           launch --type=background @KITTYMUX_HOME@/bin/mux-nav.sh 4
map ctrl+alt+5           launch --type=background @KITTYMUX_HOME@/bin/mux-nav.sh 5
map ctrl+alt+6           launch --type=background @KITTYMUX_HOME@/bin/mux-nav.sh 6
map ctrl+alt+7           launch --type=background @KITTYMUX_HOME@/bin/mux-nav.sh 7
map ctrl+alt+8           launch --type=background @KITTYMUX_HOME@/bin/mux-nav.sh 8
map ctrl+alt+9           launch --type=background @KITTYMUX_HOME@/bin/mux-nav.sh 9
# alt+N — one-hand aliases (WezTerm/mux convention), session-scoped same as
# ctrl+alt+N. Costs readline's alt-digit repeat-arg — a fair trade.
map alt+1                launch --type=background @KITTYMUX_HOME@/bin/mux-nav.sh 1
map alt+2                launch --type=background @KITTYMUX_HOME@/bin/mux-nav.sh 2
map alt+3                launch --type=background @KITTYMUX_HOME@/bin/mux-nav.sh 3
map alt+4                launch --type=background @KITTYMUX_HOME@/bin/mux-nav.sh 4
map alt+5                launch --type=background @KITTYMUX_HOME@/bin/mux-nav.sh 5
map alt+6                launch --type=background @KITTYMUX_HOME@/bin/mux-nav.sh 6
map alt+7                launch --type=background @KITTYMUX_HOME@/bin/mux-nav.sh 7
map alt+8                launch --type=background @KITTYMUX_HOME@/bin/mux-nav.sh 8
map alt+9                launch --type=background @KITTYMUX_HOME@/bin/mux-nav.sh 9
# ctrl+alt+` — flip to previously active tab (MRU, like alt-tab)
map ctrl+alt+grave_accent       goto_tab -1

map ctrl+shift+comma     move_tab_backward
map ctrl+shift+period    move_tab_forward
# ctrl+alt+shift+left — move this tab earlier (arrows follow the bar: ←/→ on a horizontal bar)
map ctrl+alt+shift+left  move_tab_backward
# ctrl+alt+shift+right — move this tab later (horizontal bar)
map ctrl+alt+shift+right move_tab_forward
# ctrl+alt+shift+up — move this tab up the list (↑/↓ on a vertical bar; both pairs always work)
map ctrl+alt+shift+up    move_tab_backward
# ctrl+alt+shift+down — move this tab down the list (vertical bar)
map ctrl+alt+shift+down  move_tab_forward

# ============================================
# PANES — vim-style nav, detach, zoom
# ============================================
map ctrl+alt+h           neighboring_window left
map ctrl+alt+j           neighboring_window down
map ctrl+alt+k           neighboring_window up
map ctrl+alt+l           neighboring_window right
# NOTE: ctrl+alt+arrows is claimed by some WMs (e.g. Hyprland's scrolling
# layout uses it for layoutmsg focus). Pane arrows live on shift+alt.
map shift+alt+left       neighboring_window left
map shift+alt+down       neighboring_window down
map shift+alt+up         neighboring_window up
map shift+alt+right      neighboring_window right
map ctrl+alt+o           nth_window -1
map ctrl+alt+d           detach_window new-tab-right
map ctrl+alt+shift+d     detach_window ask
# ctrl+alt+e — number every pane on screen, then press its digit to focus it (tmux's display-panes; two panes: jumps straight over)
map ctrl+alt+e           focus_visible_window
# ctrl+alt+shift+1..9 — focus pane N of this tab directly (the number ctrl+alt+e shows on each pane; ctrl+alt+1..9 are tabs)
map ctrl+alt+shift+1   nth_window 0
map ctrl+alt+shift+2   nth_window 1
map ctrl+alt+shift+3   nth_window 2
map ctrl+alt+shift+4   nth_window 3
map ctrl+alt+shift+5   nth_window 4
map ctrl+alt+shift+6   nth_window 5
map ctrl+alt+shift+7   nth_window 6
map ctrl+alt+shift+8   nth_window 7
map ctrl+alt+shift+9   nth_window 8
# ctrl+alt+shift+y — number every pane, press a digit to swap the current pane with that one
map ctrl+alt+shift+y     swap_with_window
# ctrl+alt+shift+; — pane controls: h/j/k/l swap with a neighbor · r rotate · s swap split sides · e equalize · a choose a pane · esc cancel
map ctrl+alt+shift+semicolon kitten @KITTYMUX_HOME@/python/pane-kit.py
map --when-focus-on title:kittymux-panes ctrl+alt+shift+semicolon close_window
# ctrl+alt+shift+j — join this tab into another as splits: pick the tab (type to filter · ⏎ joins · tab = side · ctrl+t = whole tab / this pane)
map ctrl+alt+shift+j     kitten @KITTYMUX_HOME@/python/join-kit.py
map --when-focus-on cmdline:join-kit.py ctrl+alt+shift+j close_window
# ctrl+alt+shift+q — quick look: the peek card of the agent that has waited on you longest, without leaving this tab (⏎ goes there · esc stays); kittymux peek [TAB_ID] for any tab
map ctrl+alt+shift+q     launch --type=background @KITTYMUX_HOME@/bin/kittymux peek --waiting
map --when-focus-on cmdline:peek-kit.py ctrl+alt+shift+q close_window
# ctrl+alt+shift+c — show/hide pane title bars (captions): drag handles for moving a split to a tab, another tab, or elsewhere
map ctrl+alt+shift+c     toggle_window_title_bars

# ============================================
# HUDS — location, agent usage, agent jump
# ============================================
map ctrl+alt+i           launch --type=overlay --cwd=current @KITTYMUX_HOME@/bin/mux-cwd.sh
map ctrl+alt+shift+i     launch --type=overlay --cwd=current @KITTYMUX_HOME@/bin/mux-cwd.sh --detail
map ctrl+alt+u           launch --type=overlay --title=kittymux-usage python3 @KITTYMUX_HOME@/bin/mux-usage.py
map --when-focus-on title:kittymux-usage ctrl+alt+u close_window
# agent picker: every agent pane across windows/sessions + live preview
# (ctrl+alt+g, not +a — ctrl+alt+a is Hyprland's swapcol on this setup)
map ctrl+alt+g           launch --type=overlay @KITTYMUX_HOME@/bin/mux-agents.sh
# ctrl+alt+b — sidebar command deck (hover/click, live preview, jump to tab)
map ctrl+alt+b           kitten @KITTYMUX_HOME@/python/sidebar-kit.py
# ctrl+alt+shift+b — toggle the sidebar deck as a persistent docked panel (Wayland)
map ctrl+alt+shift+b     launch --type=background @KITTYMUX_HOME@/bin/mux-panel toggle
# ctrl+alt+y — jump to the next agent waiting on you (round-robin, longest-waiting first)
map ctrl+alt+y           launch --type=background @KITTYMUX_HOME@/bin/mux-agents.sh --next-waiting
# ctrl+alt+shift+g — new agent in its own git worktree + tab
map ctrl+alt+shift+g     launch --type=overlay --cwd=current @KITTYMUX_HOME@/bin/mux-agent-new
# send a prompt to a background agent pane without switching focus
map ctrl+alt+semicolon   launch --type=overlay @KITTYMUX_HOME@/bin/mux-send.sh
# ctrl+alt+v — pick: what needs you, every agent, closed conversations and a new agent in ONE searchable list (rofi/fuzzel from your WM: `kittymux pick --menu rofi`)
map ctrl+alt+v           launch --type=overlay --title kittymux-pick @KITTYMUX_HOME@/bin/kittymux pick
map --when-focus-on title:kittymux-pick ctrl+alt+v close_window
# ctrl+alt+shift+u — reopen the agent conversation you closed last (it asks before resuming)
map ctrl+alt+shift+u     launch --type=background @KITTYMUX_HOME@/bin/kittymux reopen
# ctrl+alt+shift+o — spawn mode: then a letter starts that agent in a new tab (shift+letter: split right) — c claude · x codex · d devin · u cursor · o opencode · a agy · g grok
map --new-mode spawn --on-action end --on-unknown end --timeout 3.0 ctrl+alt+shift+o
# spawn claude in a new tab (shift: split right)
map --mode spawn c launch --type=background @KITTYMUX_HOME@/bin/kittymux spawn claude
map --mode spawn shift+c launch --type=background @KITTYMUX_HOME@/bin/kittymux spawn claude --vsplit
# spawn codex in a new tab (shift: split right)
map --mode spawn x launch --type=background @KITTYMUX_HOME@/bin/kittymux spawn codex
map --mode spawn shift+x launch --type=background @KITTYMUX_HOME@/bin/kittymux spawn codex --vsplit
# spawn devin in a new tab (shift: split right)
map --mode spawn d launch --type=background @KITTYMUX_HOME@/bin/kittymux spawn devin
map --mode spawn shift+d launch --type=background @KITTYMUX_HOME@/bin/kittymux spawn devin --vsplit
# spawn cursor-agent in a new tab (shift: split right)
map --mode spawn u launch --type=background @KITTYMUX_HOME@/bin/kittymux spawn cursor-agent
map --mode spawn shift+u launch --type=background @KITTYMUX_HOME@/bin/kittymux spawn cursor-agent --vsplit
# spawn opencode in a new tab (shift: split right)
map --mode spawn o launch --type=background @KITTYMUX_HOME@/bin/kittymux spawn opencode
map --mode spawn shift+o launch --type=background @KITTYMUX_HOME@/bin/kittymux spawn opencode --vsplit
# spawn agy in a new tab (shift: split right)
map --mode spawn a launch --type=background @KITTYMUX_HOME@/bin/kittymux spawn agy
map --mode spawn shift+a launch --type=background @KITTYMUX_HOME@/bin/kittymux spawn agy --vsplit
# spawn grok in a new tab (shift: split right)
map --mode spawn g launch --type=background @KITTYMUX_HOME@/bin/kittymux spawn grok
map --mode spawn shift+g launch --type=background @KITTYMUX_HOME@/bin/kittymux spawn grok --vsplit
# per-window activity state feeding the picker's busy/waiting markers
watcher @KITTYMUX_HOME@/python/pane-state.py
# ctrl+alt+shift+e — move this window's bar: left → bottom → top → right
map ctrl+alt+shift+e     launch --type=background @KITTYMUX_HOME@/bin/mux-edge.sh
# ctrl+alt+backslash — this window's bar: sidebar → slim rail → hidden (zen), like a browser sidebar
map ctrl+alt+backslash   launch --type=background @KITTYMUX_HOME@/bin/kittymux layout mode cycle
# ctrl+alt+shift+[ — narrower sidebar
map ctrl+alt+shift+bracketleft  launch --type=background @KITTYMUX_HOME@/bin/kittymux layout width -2
# ctrl+alt+shift+] — wider sidebar
map ctrl+alt+shift+bracketright launch --type=background @KITTYMUX_HOME@/bin/kittymux layout width +2
# ctrl+alt+shift+l — pick a bar layout preset (sidebar, rail, right, bottom, top, zen)
map ctrl+alt+shift+l     launch --type=overlay @KITTYMUX_HOME@/bin/kittymux layout pick

# ============================================
# RESIZE, SCROLLBACK & HELP
# ctrl+alt+/         — keymap overlay: searchable, scrollable, every key / gesture / command (press again or q/esc to close)
# ctrl+alt+shift+/   — last command's output in pager
# ctrl+alt+q         — close current pane (confirms if a process runs)
# ctrl+alt+[ / ]     — jump between shell prompts in scrollback
# alt+shift+h/l/j/k  — resize pane narrower/wider/taller/shorter
# ============================================
map ctrl+alt+slash        launch --type=overlay --title kittymux-keys python3 @KITTYMUX_HOME@/bin/mux-keys.py
# pressing it again while the overlay is open closes it (otherwise the key would stack a second overlay on top)
map --when-focus-on title:kittymux-keys ctrl+alt+slash close_window
map ctrl+alt+shift+slash  show_last_command_output
map ctrl+alt+q            close_window_with_confirmation
# ctrl+alt+PgUp / PgDn — scroll the scrollback a page; ctrl+alt+Home / End — oldest output / back to the live screen
map ctrl+alt+page_up      scroll_page_up
map ctrl+alt+page_down    scroll_page_down
map ctrl+alt+home         scroll_home
map ctrl+alt+end          scroll_end
map ctrl+alt+bracketleft  scroll_to_prompt -1
map ctrl+alt+bracketright scroll_to_prompt 1
map alt+shift+h           resize_window narrower 1
map alt+shift+l           resize_window wider 1
map alt+shift+j           resize_window taller 1
map alt+shift+k           resize_window shorter 1

# ============================================
# LAYOUTS
# ============================================
map ctrl+alt+space       next_layout
map ctrl+alt+z           layout_action maximize
# ctrl+alt+0: rebalance (ctrl+alt+equal collides with Hyprland colresize)
map ctrl+alt+0           layout_action equalize

# ============================================
# SESSIONS — Kitty Home is the one shortcut to remember
# ============================================
map ctrl+shift+space     launch --type=overlay @KITTYMUX_HOME@/bin/mux-sessionizer
map ctrl+alt+shift+n     launch --type=overlay @KITTYMUX_HOME@/bin/mux-sessionizer
map ctrl+alt+shift+m     launch --type=overlay @KITTYMUX_HOME@/bin/mux-movetab.sh
map ctrl+alt+shift+s     launch --type=overlay @KITTYMUX_HOME@/bin/mux-save.sh
map ctrl+alt+shift+a     launch --type=background @KITTYMUX_HOME@/bin/mux-cycle.sh last
map ctrl+alt+comma       launch --type=background @KITTYMUX_HOME@/bin/mux-cycle.sh prev
map ctrl+alt+period      launch --type=background @KITTYMUX_HOME@/bin/mux-cycle.sh next

# ============================================
# PROJECT PICKER + SCRATCH CONFIG TAB
# ============================================
map ctrl+alt+shift+p     launch --type=overlay @KITTYMUX_HOME@/bin/mux-projects.sh

# ctrl+alt+shift+h / k / v / z / f / x are NOT ours: if your own kitty config maps them (quick config edits for Hyprland, kitty, nvim and zsh; a font toggle;
# a screenshot) they keep working exactly as you wrote them. kitty reads this file AFTER yours and the last definition wins, so mapping one of them here would
# silently switch yours off. kittymux took its pane-title-bar toggle to ctrl+alt+shift+c and its pane swap to ctrl+alt+shift+y for that reason;
# `kittymux doctor` lists any chord that both configs define.

# ============================================
# OTHER
# ============================================
map ctrl+shift+alt+r     combine : load_config_file : launch --type=background notify-send -i kitty -t 2000 "Kitty" "Config reloaded"
map ctrl+alt+shift+w     close_tab
map shift+enter          send_text normal,application \x1b[13;2u
